CC	= gcc
CFLAGS	= -g -Wall

all: problem1 problem2

problem1: problem1.c
	$(CC) $(CFLAGS) -o problem1.o problem1.c
	
problem2: problem2.c
	$(CC) $(CFLAGS) -o problem2.o problem2.c

clean:
	rm -f *~ *.o a.out core *.txt
